apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "omegion"
        vault.hashicorp.com/auth-path: "auth/kubernetes/cluster-1"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-github: "github/token"
        vault.hashicorp.com/agent-inject-template-github: |
          {{ with secret "github/token" -}}
            export GITHUB_TOKEN="{{ .Data.data.repo_read_only }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-github-oauth: "github/oauth/blog"
        vault.hashicorp.com/agent-inject-template-github-oauth: |
          {{ with secret "github/oauth/blog" -}}
            export GITHUB_CLIENT_ID="{{ .Data.data.client_id }}"
            export GITHUB_CLIENT_SECRET="{{ .Data.data.secret_id }}"
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: blog
          image: ghcr.io/omegion/blog:v1.38.0
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - >-
              source /vault/secrets/github;source /vault/secrets/github-oauth; yarn start
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 75m
              memory: 50Mi
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
  strategy:
    blueGreen:
      activeService: blog-stable
      previewService: blog-preview
      autoPromotionEnabled: false
