---
apiVersion: v1
kind: Service
metadata:
  name: blog-stable
  labels:
    app: blog-stable
spec:
  ports:
    - name: app
      port: 80
      targetPort: 80
  selector:
    app: blog
---
apiVersion: v1
kind: Service
metadata:
  name: blog-preview
  labels:
    app: blog-preview
spec:
  ports:
    - name: app
      port: 80
      targetPort: 80
  selector:
    app: blog
