---
apiVersion: v1
kind: Service
metadata:
  name: blog-stable
spec:
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-preview
spec:
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 80
