name: Publish

on:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          githubToken: ${{ secrets.GT_VAULT_AUTH_TOKEN }}
          secrets: |
            github/data/token registry_write | GITHUB_REGISTRY_TOKEN ;
            argocd/data/token admin | ARGOCD_TOKEN ;


      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: |
          export GITHUB_TOKEN=${{steps.secrets.outputs.GITHUB_REGISTRY_TOKEN}}
          yarn generate || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

